import React from 'react';
import MindMap from './MindMap';
import html2pdf from 'html2pdf.js';
import { Download } from 'lucide-react';

const ChatBubble = ({ message, onImageClick }) => {
    
    // Hàm xử lý xuất PDF (Outbound)
    const handleDownloadPDF = (content, filename) => {
        const element = document.createElement('div');
        element.innerHTML = `
            <div style="font-family: Arial, sans-serif; padding: 20px;">
                <h2 style="text-align: center; color: #4a90e2;">Tài liệu Sinh bởi AI Tutor</h2>
                <hr/>
                <div style="white-space: pre-wrap; font-size: 14px; line-height: 1.6;">${content.replace(/\n/g, '<br/>')}</div>
                <hr/>
                <p style="text-align: right; font-size: 10px; color: #888;">Generated by VKU KMS System</p>
            </div>
        `;
        const opt = {
            margin:       0.5,
            filename:     `${filename}.pdf`,
            image:        { type: 'jpeg', quality: 0.98 },
            html2canvas:  { scale: 2 },
            jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
        };
        html2pdf().from(element).set(opt).save();
    };
    
    // Hàm siêu quét: Tìm và bóc tách đoạn ```mermaid ... ```
    const renderContent = (text) => {
        if (!text) return null;

        // 1. Kiểm tra Document Generation (Outbound)
        const docRegex = /\[DOCUMENT_START\]([\s\S]*?)\[DOCUMENT_END\]/i;
        const docMatch = text.match(docRegex);

        if (docMatch) {
            const fullMatch = docMatch[0];
            const pureContent = docMatch[1].trim();
            const textParts = text.split(fullMatch);

            return (
                <>
                    {textParts[0] && <p style={{ whiteSpace: 'pre-wrap' }}>{textParts[0].trim()}</p>}
                    
                    <div style={{
                        backgroundColor: '#252530',
                        border: '1px solid #4dd0e1',
                        borderRadius: '10px',
                        padding: '15px',
                        marginTop: '10px',
                        marginBottom: '10px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between'
                    }}>
                        <div>
                            <h4 style={{ margin: 0, color: '#4dd0e1', fontSize: '15px' }}>📄 Bộ tài liệu đã sẵn sàng</h4>
                            <p style={{ margin: '5px 0 0 0', fontSize: '12px', color: '#888' }}>
                                AI Tutor đã tạo xong tài liệu theo yêu cầu của bạn.
                            </p>
                        </div>
                        <button 
                            onClick={() => handleDownloadPDF(pureContent, 'Tai-Lieu-AI')}
                            style={{
                                display: 'flex', alignItems: 'center', gap: '5px',
                                backgroundColor: '#4dd0e1', color: '#000',
                                border: 'none', padding: '8px 15px', borderRadius: '5px',
                                cursor: 'pointer', fontWeight: 'bold', fontSize: '13px'
                            }}
                        >
                            <Download size={16} /> Tải PDF
                        </button>
                    </div>

                    {textParts[1] && <p style={{ whiteSpace: 'pre-wrap', marginTop: '10px' }}>{textParts[1].trim()}</p>}
                </>
            );
        }

        const mermaidRegex = /```mermaid([\s\S]*?)```/i;
        const match = text.match(mermaidRegex);

        if (match) {
            const fullMatch = match[0]; // Cục ```mermaid...```
            const pureCode = match[1].trim(); // Chỉ lấy ruột code bên trong
            
            // Cắt chuỗi text thành 2 mảng: Trước sơ đồ và Sau sơ đồ
            const textParts = text.split(fullMatch);

            return (
                <>
                    {/* Phần chữ AI nói TRƯỚC sơ đồ */}
                    {textParts[0] && <p style={{ whiteSpace: 'pre-wrap' }}>{textParts[0].trim()}</p>}
                    
                    {/* Máy in sơ đồ */}
                    <MindMap chartCode={pureCode} onImageClick={onImageClick} />
                    
                    {/* Phần chữ AI nói SAU sơ đồ */}
                    {textParts[1] && <p style={{ whiteSpace: 'pre-wrap', marginTop: '10px' }}>{textParts[1].trim()}</p>}
                </>
            );
        }

        // Nếu không có sơ đồ thì in chữ bình thường
        return <p style={{ whiteSpace: 'pre-wrap' }}>{text}</p>;
    };

    return (
        <div className={`chat-bubble ${message.sender}`}>
            <div className="avatar">{message.sender === 'ai' ? 'AI' : 'Me'}</div>
            <div className="text-content">
                {message.image && (
                    <div style={{ marginBottom: message.text ? '10px' : '0' }}>
                        <img 
                            src={message.image} 
                            alt="Uploaded" 
                            style={{ maxWidth: '100%', borderRadius: '8px', maxHeight: '250px', objectFit: 'contain', cursor: 'pointer' }} 
                            onClick={() => onImageClick && onImageClick(message.image)}
                        />
                    </div>
                )}
                {renderContent(message.text)}
            </div>
        </div>
    );
};

export default ChatBubble;